### ISSUE TITLE
Issue with run gradlew checkstyleMain

### ISSUE THREAD

**Issue by adam-ky** [nus-cs2103-AY2122S1/forum#158]
I tried to run ./gradlew checkstyleMain but got this:

```java
> Task :checkstyleMain FAILED

FAILURE: Build failed with an exception.
> Unable to create Root Module: config {C:\Users\Adam\Desktop\Project Materials\iP\config\checkstyle\checkstyle.xml}, classpath {C:\Users\Adam\Desktop\Project Materials\iP\build\classe
s\java\main;C:\Users\Adam\Desktop\Project Materials\iP\build\resources\main}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date

```

Even though I have added the config files by copying them over from AB3 repo (as shown below), checkstyleMain still failed 😢
 
![image](https://user-images.githubusercontent.com/69505439/131546968-9043efaf-5ede-4923-9b4c-8ba0bb180726.png)

Could anyone help me out *please*? 🙏

**Comment by clyveycui** [comment]
Have you tried going into Intellij File > Invalidate Caches / Restart > Invalidate and Restart ?

**Comment by rickyaandrew** [comment]
maybe you can try cleaning it by using the 'gradlew clean' command, then restart it. somehow it worked for me

**Comment by adam-ky** [comment]
> Have you tried going into Intellij File > Invalidate Caches / Restart > Invalidate and Restart ?

Unfortunately, the same error still persists

> maybe you can try cleaning it by using the 'gradlew clean' command, then restart it. somehow it worked for me

Same for after running gradlew clean

```java
PS C:\Users\Adam\Desktop\Project Materials\iP> ./gradlew clean

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
PS C:\Users\Adam\Desktop\Project Materials\iP> ./gradlew checkstyleMain
> Task :checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> Unable to create Root Module: config {C:\Users\Adam\Desktop\Project Materials\iP\config\checkstyle\checkstyle.xml}, classpath {C:\Users\Adam\Desktop\Project Materials\iP\build\classes\java\main;C:\Users\Adam\Desktop\Project Materi
als\iP\build\resources\main}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed
```

thanks for helping but I still can't seem to find a possible fix 😪

**Comment by YaleChen299** [comment]
Hi, maybe you can try running the suggested `--stacktrace` option to get more useful information.

A possible bug that I can think of is:
maybe the main class specified in `build.gradle` is different from your package name.
This happened to me and I couldn't run `checkstyleMain` and `run`.

**Comment by SkyBlaise99** [comment]
Did you add `checkstyle` related stuffs into `build.gradle`?
``` gradle
plugins {
    // other ids
    id 'checkstyle'
}

// other stuffs

checkstyle {
    toolVersion = '8.29'
}
```

Also I think when I copied the `.xml` files from AB3 both showed some errors and I had to resolve them first before my checkstyle can run. Perhaps take a look into the 2 `.xml` files and see if Intelij shows any errors? The part that show error for me is line 3-4.
![image](https://user-images.githubusercontent.com/69448615/131619900-096a893d-b36f-4a77-9101-36327512fe06.png)

**Comment by adam-ky** [comment]
> A possible bug that I can think of is:
> maybe the main class specified in `build.gradle` is different from your package name.
> This happened to me and I couldn't run `checkstyleMain` and `run`.

Hi thanks for this suggestion, I changed the package name from the original `seedu.duke.Duke` to `duke.Duke`to match my own package name. I was able to run `run` but not `checkstyleMain` and the error still persists.

```java
application {
    mainClassName = "duke.Duke"
}
```

> Also I think when I copied the .xml files from AB3 both showed some errors and I had to resolve them first before my checkstyle can run. Perhaps take a look into the 2 .xml files and see if Intelij shows any errors? The part that show error for me is line 3-4.

Yes I have resolved those same issues you mentioned before, but unfortunately it didn't help.
```java
FAILURE: Build failed with an exception.
> Unable to create Root Module: config {C:\Users\Adam\Desktop\Project Materials\iP\config\checkstyle\checkstyle.xml}, classpath {C:\Users\Adam\Desktop\Project Materials\iP\build\classe
s\java\main;C:\Users\Adam\Desktop\Project Materials\iP\build\resources\main}.
```

Thanks to everyone who've helped so far but I still can't seem to fix it :sweat_smile:

**Comment by damithc** [comment]
> Thanks to everyone who've helped so far but I still can't seem to fix it 😅

@adam-ky Perhaps you can push the current state of the code to your fork (can push to a separate branch) so that others can try to reproduce the problem using a clone of your fork?

**Comment by adam-ky** [comment]
> @adam-ky Perhaps you can push the current state of the code to your fork (can push to a separate branch) so that others can try to reproduce the problem using a clone of your fork?

Thank you prof for the suggestion, I have pushed a separate branch of my current code to my fork.
Thanks in advance to anyone who helps 😃

**Comment by waynetee** [comment]
@adam-ky Where did you get your checkstyle config from? Did you use the one from AB3?

**Comment by adam-ky** [comment]
> @adam-ky Where did you get your checkstyle config from? Did you use the one from AB3?

Yes, I copied them over from AB3

**Comment by waynetee** [comment]
Like from here?
https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml

**Comment by qinguorui2001** [comment]
are checkstyle.xml and suppressions.xml still shown as red texts?

**Comment by SkyBlaise99** [comment]
I solved your issue, you didn't configure the checkstyle version and files here.
![image](https://user-images.githubusercontent.com/69448615/131650172-32ea3497-ba2c-47c8-a278-b28faa204a5e.png)
 You can just follow the steps [here](https://se-education.org/guides/tutorials/checkstyle.html#using-checkstyle-idea-plugin), remember to change version to `8.29`.

**Comment by adam-ky** [comment]
>You can just follow the steps here, remember to change version to 8.29.

Thank you it works now. I believe my whole issue started from what @YaleChen299 mentioned which led to a bug in
adding the configuration file as well:
> A possible bug that I can think of is:
maybe the main class specified in build.gradle is different from your package name.
This happened to me and I couldn't run checkstyleMain and run.

Now that I've corrected both issues, the `checkstyleMain` works now. Thank you, everyone! 🥳
